{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Mon Dec  2 00:18:16 2013) by ROOT version5.32/00
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",587,123,700,502);
   Canvas_1->Range(-1.247756,-227.9684,1.251346,2023.219);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","nom",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,280.0617);
   DefaultTrue_allWcosTheta->SetBinContent(2,934.6046);
   DefaultTrue_allWcosTheta->SetBinContent(3,1255.268);
   DefaultTrue_allWcosTheta->SetBinContent(4,1435.221);
   DefaultTrue_allWcosTheta->SetBinContent(5,1455.059);
   DefaultTrue_allWcosTheta->SetBinContent(6,1319.022);
   DefaultTrue_allWcosTheta->SetBinContent(7,1054.88);
   DefaultTrue_allWcosTheta->SetBinContent(8,791.727);
   DefaultTrue_allWcosTheta->SetBinContent(9,430.8246);
   DefaultTrue_allWcosTheta->SetBinContent(10,244.7469);
   DefaultTrue_allWcosTheta->SetBinError(1,31.52123);
   DefaultTrue_allWcosTheta->SetBinError(2,43.27309);
   DefaultTrue_allWcosTheta->SetBinError(3,48.46011);
   DefaultTrue_allWcosTheta->SetBinError(4,51.84056);
   DefaultTrue_allWcosTheta->SetBinError(5,54.80855);
   DefaultTrue_allWcosTheta->SetBinError(6,51.65311);
   DefaultTrue_allWcosTheta->SetBinError(7,41.12341);
   DefaultTrue_allWcosTheta->SetBinError(8,37.5735);
   DefaultTrue_allWcosTheta->SetBinError(9,29.99039);
   DefaultTrue_allWcosTheta->SetBinError(10,32.79785);
   DefaultTrue_allWcosTheta->SetMinimum(0);
   DefaultTrue_allWcosTheta->SetMaximum(1800);
   DefaultTrue_allWcosTheta->SetEntries(18869.29);
   
   TPaveStats *ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 18869  ");
   text = ptstats->AddText("Mean  = -0.07991");
   text = ptstats->AddText("RMS   = 0.4387");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);
   DefaultTrue_allWcosTheta->SetLineColor(2);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->Draw("");
   
   TPaveText *pt = new TPaveText(0.2910057,0.9342405,0.3828448,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("nom");
   pt->Draw();
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","down",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,262.5956);
   DefaultTrue_allWcosTheta->SetBinContent(2,892.1869);
   DefaultTrue_allWcosTheta->SetBinContent(3,1174.8);
   DefaultTrue_allWcosTheta->SetBinContent(4,1335.831);
   DefaultTrue_allWcosTheta->SetBinContent(5,1335.5);
   DefaultTrue_allWcosTheta->SetBinContent(6,1189.898);
   DefaultTrue_allWcosTheta->SetBinContent(7,914.9438);
   DefaultTrue_allWcosTheta->SetBinContent(8,684.0194);
   DefaultTrue_allWcosTheta->SetBinContent(9,380.7135);
   DefaultTrue_allWcosTheta->SetBinContent(10,221.4588);
   DefaultTrue_allWcosTheta->SetBinError(1,31.34793);
   DefaultTrue_allWcosTheta->SetBinError(2,42.96627);
   DefaultTrue_allWcosTheta->SetBinError(3,47.93941);
   DefaultTrue_allWcosTheta->SetBinError(4,51.2391);
   DefaultTrue_allWcosTheta->SetBinError(5,54.1239);
   DefaultTrue_allWcosTheta->SetBinError(6,50.86745);
   DefaultTrue_allWcosTheta->SetBinError(7,40.04802);
   DefaultTrue_allWcosTheta->SetBinError(8,36.66853);
   DefaultTrue_allWcosTheta->SetBinError(9,29.46464);
   DefaultTrue_allWcosTheta->SetBinError(10,32.57564);
   DefaultTrue_allWcosTheta->SetEntries(18869.29);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 18869  ");
   text = ptstats->AddText("Mean  = -0.09199");
   text = ptstats->AddText("RMS   = 0.4383");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);
   DefaultTrue_allWcosTheta->SetLineColor(8);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->Draw("sames");
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","up",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,297.5278);
   DefaultTrue_allWcosTheta->SetBinContent(2,977.0222);
   DefaultTrue_allWcosTheta->SetBinContent(3,1335.737);
   DefaultTrue_allWcosTheta->SetBinContent(4,1534.611);
   DefaultTrue_allWcosTheta->SetBinContent(5,1574.619);
   DefaultTrue_allWcosTheta->SetBinContent(6,1448.146);
   DefaultTrue_allWcosTheta->SetBinContent(7,1194.817);
   DefaultTrue_allWcosTheta->SetBinContent(8,899.4345);
   DefaultTrue_allWcosTheta->SetBinContent(9,480.9356);
   DefaultTrue_allWcosTheta->SetBinContent(10,268.035);
   DefaultTrue_allWcosTheta->SetBinError(1,31.80796);
   DefaultTrue_allWcosTheta->SetBinError(2,43.77967);
   DefaultTrue_allWcosTheta->SetBinError(3,49.31574);
   DefaultTrue_allWcosTheta->SetBinError(4,52.82779);
   DefaultTrue_allWcosTheta->SetBinError(5,55.931);
   DefaultTrue_allWcosTheta->SetBinError(6,52.93664);
   DefaultTrue_allWcosTheta->SetBinError(7,42.8558);
   DefaultTrue_allWcosTheta->SetBinError(8,39.03518);
   DefaultTrue_allWcosTheta->SetBinError(9,30.84674);
   DefaultTrue_allWcosTheta->SetBinError(10,33.1649);
   DefaultTrue_allWcosTheta->SetEntries(18869.29);
   
   ptstats = new TPaveStats(0.78,0.775,0.98,0.935,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.0368);
   text = ptstats->AddText("Entries = 18869  ");
   text = ptstats->AddText("Mean  = -0.06979");
   text = ptstats->AddText("RMS   = 0.4389");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   DefaultTrue_allWcosTheta->SetLineColor(ci);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->Draw("sames");
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
