cd ele2/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele2/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele3/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele4/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele5/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele6/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele7/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele8/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele9/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele10/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele11/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele12/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele13/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele14/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele15/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele16/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele17/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele18/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele19/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele20/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele21/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele22/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele23/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele24/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele25/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele26/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele27/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele28/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele29/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele30/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele31/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele32/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele33/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele34/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele35/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele36/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele37/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele38/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele39/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele40/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele41/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele42/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele43/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele44/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele45/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele46/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele47/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele48/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele49/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele50/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele51/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
cd ele52/; source eOneDfit_qcdfree.sh; source OneDfit_qcdfree.sh; cd -
