cd  pdf1/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf2/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf3/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf4/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf5/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf6/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf7/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf8/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf9/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf10/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf11/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf12/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf13/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf14/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf15/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf16/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf17/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf18/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf19/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf20/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf21/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf22/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf23/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf24/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf25/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf26/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf27/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf28/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf29/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf30/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf31/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf32/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf33/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf34/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf35/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf36/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf37/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf38/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf39/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf40/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf41/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf42/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf43/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf44/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf45/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf46/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf47/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf48/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf49/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf50/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf51/; source eweighter.sh; source muweighter.sh; cd -
cd  pdf52/; source eweighter.sh; source muweighter.sh; cd -
