cd  pdf1/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf2/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf3/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf4/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf5/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf6/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf7/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf8/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf9/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf10/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf11/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf12/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf13/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf14/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf15/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf16/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf17/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf18/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf19/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf20/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf21/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf22/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf23/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf24/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf25/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf26/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf27/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf28/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf29/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf30/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf31/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf32/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf33/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf34/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf35/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf36/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf37/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf38/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf39/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf40/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf41/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf42/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf43/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf44/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf45/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf46/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf47/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf48/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf49/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf50/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf51/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
cd  pdf52/; ln -s ../SystFitCominedEle; ln -s ../SystFitCominedMu; ln -s ../SystFitComined; cd -
