{
//=========Macro generated from canvas: Canvas_1/Canvas_1
//=========  (Mon Dec  2 00:43:25 2013) by ROOT version5.32/00
   TCanvas *Canvas_1 = new TCanvas("Canvas_1", "Canvas_1",501,135,700,502);
   Canvas_1->Range(-1.25,-500,1.25,4500);
   Canvas_1->SetFillColor(0);
   Canvas_1->SetBorderMode(0);
   Canvas_1->SetBorderSize(2);
   Canvas_1->SetFrameBorderMode(0);
   Canvas_1->SetFrameBorderMode(0);
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","nominal",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,350.7277);
   DefaultTrue_allWcosTheta->SetBinContent(2,826.8169);
   DefaultTrue_allWcosTheta->SetBinContent(3,1055.453);
   DefaultTrue_allWcosTheta->SetBinContent(4,1228.184);
   DefaultTrue_allWcosTheta->SetBinContent(5,1326.482);
   DefaultTrue_allWcosTheta->SetBinContent(6,1549.016);
   DefaultTrue_allWcosTheta->SetBinContent(7,1510.64);
   DefaultTrue_allWcosTheta->SetBinContent(8,1846.835);
   DefaultTrue_allWcosTheta->SetBinContent(9,2161.505);
   DefaultTrue_allWcosTheta->SetBinContent(10,2656.767);
   DefaultTrue_allWcosTheta->SetBinError(1,27.25483);
   DefaultTrue_allWcosTheta->SetBinError(2,43.41907);
   DefaultTrue_allWcosTheta->SetBinError(3,52.05538);
   DefaultTrue_allWcosTheta->SetBinError(4,55.36797);
   DefaultTrue_allWcosTheta->SetBinError(5,57.7487);
   DefaultTrue_allWcosTheta->SetBinError(6,70.44197);
   DefaultTrue_allWcosTheta->SetBinError(7,63.55423);
   DefaultTrue_allWcosTheta->SetBinError(8,75.9756);
   DefaultTrue_allWcosTheta->SetBinError(9,85.87304);
   DefaultTrue_allWcosTheta->SetBinError(10,101.7742);
   DefaultTrue_allWcosTheta->SetMinimum(0);
   DefaultTrue_allWcosTheta->SetMaximum(4000);
   DefaultTrue_allWcosTheta->SetEntries(17214.63);
   
   TPaveStats *ptstats = new TPaveStats(0.002873563,0.835443,0.204023,0.9957806,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   TText *text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.03687764);
   text = ptstats->AddText("Entries = 17215  ");
   text = ptstats->AddText("Mean  = 0.2452");
   text = ptstats->AddText("RMS   = 0.5297");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);
   DefaultTrue_allWcosTheta->SetLineColor(2);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->DrawNormalized("");
   
   TPaveText *pt = new TPaveText(0.4799425,0.94,0.6306897,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetTextFont(42);
   text = pt->AddText("nominal");
   pt->Draw();
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","down",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,281.0902);
   DefaultTrue_allWcosTheta->SetBinContent(2,747.3626);
   DefaultTrue_allWcosTheta->SetBinContent(3,956.6724);
   DefaultTrue_allWcosTheta->SetBinContent(4,1123.268);
   DefaultTrue_allWcosTheta->SetBinContent(5,1224.02);
   DefaultTrue_allWcosTheta->SetBinContent(6,1437.044);
   DefaultTrue_allWcosTheta->SetBinContent(7,1364.309);
   DefaultTrue_allWcosTheta->SetBinContent(8,1648.045);
   DefaultTrue_allWcosTheta->SetBinContent(9,1889.09);
   DefaultTrue_allWcosTheta->SetBinContent(10,2209.492);
   DefaultTrue_allWcosTheta->SetBinError(1,26.86006);
   DefaultTrue_allWcosTheta->SetBinError(2,43.13747);
   DefaultTrue_allWcosTheta->SetBinError(3,51.76349);
   DefaultTrue_allWcosTheta->SetBinError(4,55.07655);
   DefaultTrue_allWcosTheta->SetBinError(5,57.4759);
   DefaultTrue_allWcosTheta->SetBinError(6,70.19773);
   DefaultTrue_allWcosTheta->SetBinError(7,63.20008);
   DefaultTrue_allWcosTheta->SetBinError(8,75.5732);
   DefaultTrue_allWcosTheta->SetBinError(9,85.38507);
   DefaultTrue_allWcosTheta->SetBinError(10,101.0978);
   DefaultTrue_allWcosTheta->SetEntries(11894.63);
   
   ptstats = new TPaveStats(0.002873563,0.835443,0.204023,0.9957806,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.03687764);
   text = ptstats->AddText("Entries = 11895  ");
   text = ptstats->AddText("Mean  = 0.2336");
   text = ptstats->AddText("RMS   = 0.5238");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);
   DefaultTrue_allWcosTheta->SetLineColor(8);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->DrawNormalized("sames");
   
   TH1D *DefaultTrue_allWcosTheta = new TH1D("DefaultTrue_allWcosTheta","up",10,-1,1);
   DefaultTrue_allWcosTheta->SetBinContent(1,420.3653);
   DefaultTrue_allWcosTheta->SetBinContent(2,906.2712);
   DefaultTrue_allWcosTheta->SetBinContent(3,1154.234);
   DefaultTrue_allWcosTheta->SetBinContent(4,1333.101);
   DefaultTrue_allWcosTheta->SetBinContent(5,1428.945);
   DefaultTrue_allWcosTheta->SetBinContent(6,1660.988);
   DefaultTrue_allWcosTheta->SetBinContent(7,1656.97);
   DefaultTrue_allWcosTheta->SetBinContent(8,2045.624);
   DefaultTrue_allWcosTheta->SetBinContent(9,2433.919);
   DefaultTrue_allWcosTheta->SetBinContent(10,3104.043);
   DefaultTrue_allWcosTheta->SetBinError(1,28.40624);
   DefaultTrue_allWcosTheta->SetBinError(2,44.25313);
   DefaultTrue_allWcosTheta->SetBinError(3,52.92138);
   DefaultTrue_allWcosTheta->SetBinError(4,56.23316);
   DefaultTrue_allWcosTheta->SetBinError(5,58.55946);
   DefaultTrue_allWcosTheta->SetBinError(6,71.16967);
   DefaultTrue_allWcosTheta->SetBinError(7,64.60505);
   DefaultTrue_allWcosTheta->SetBinError(8,77.17021);
   DefaultTrue_allWcosTheta->SetBinError(9,87.32061);
   DefaultTrue_allWcosTheta->SetBinError(10,103.7768);
   DefaultTrue_allWcosTheta->SetEntries(17214.63);
   
   ptstats = new TPaveStats(0.01149425,0.8080169,0.2126437,0.9683544,"brNDC");
   ptstats->SetName("stats");
   ptstats->SetBorderSize(1);
   ptstats->SetFillColor(0);
   ptstats->SetTextAlign(12);
   ptstats->SetTextFont(42);
   text = ptstats->AddText("DefaultTrue_allWcosTheta");
   text->SetTextSize(0.03687764);
   text = ptstats->AddText("Entries = 17215  ");
   text = ptstats->AddText("Mean  = 0.2545");
   text = ptstats->AddText("RMS   = 0.5342");
   ptstats->SetOptStat(1111);
   ptstats->SetOptFit(0);
   ptstats->Draw();
   DefaultTrue_allWcosTheta->GetListOfFunctions()->Add(ptstats);
   ptstats->SetParent(DefaultTrue_allWcosTheta);

   Int_t ci;   // for color index setting
   ci = TColor::GetColor("#000099");
   DefaultTrue_allWcosTheta->SetLineColor(ci);
   DefaultTrue_allWcosTheta->SetLineWidth(2);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitle("cos(#theta*)");
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetXaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetXaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetYaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetYaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelFont(42);
   DefaultTrue_allWcosTheta->GetZaxis()->SetLabelSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleSize(0.035);
   DefaultTrue_allWcosTheta->GetZaxis()->SetTitleFont(42);
   DefaultTrue_allWcosTheta->DrawNormalized("sames");
   Canvas_1->Modified();
   Canvas_1->cd();
   Canvas_1->SetSelected(Canvas_1);
}
