gedit btag/MGOneDfit.sh; 
gedit ctag/MGOneDfit.sh; 
gedit JER/MGOneDfit.sh; 
gedit JES/MGOneDfit.sh; 
gedit lumi/MGOneDfit.sh; 
gedit mass/MGOneDfit.sh; 
gedit MET/MGOneDfit.sh; 
gedit pu/MGOneDfit.sh; 
gedit Q2/MGOneDfit.sh; 
gedit ewknorm/MGOneDfit.sh; 
gedit qcdnorm/MGOneDfit.sh; 
gedit tt/MGOneDfit.sh; 
gedit t/MGOneDfit.sh; 

cd btag; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd ctag; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd JER; ln -s ../MGSystFitCominedJESMu MGSystFitCominedJESMu;; cd -;
cd JES; ln -s ../MGSystFitCominedJESMu MGSystFitCominedJESMu;; cd -;
cd lumi; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd mass; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd MET; ln -s ../MGSystFitCominedJESMu MGSystFitCominedJESMu;; cd -;
cd pu; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd Q2; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd ewknorm; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd qcdnorm; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd tt; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;
cd t; ln -s ../MGSystFitCominedMu MGSystFitCominedMu;; cd -;

cd btag; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd ctag; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd JER; ln -s ../MGSystFitCominedJES MGSystFitCominedJES;; cd -;
cd JES; ln -s ../MGSystFitCominedJES MGSystFitCominedJES;; cd -;
cd lumi; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd mass; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd MET; ln -s ../MGSystFitCominedJES MGSystFitCominedJES;; cd -;
cd pu; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd Q2; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd ewknorm; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd qcdnorm; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd tt; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
cd t; ln -s ../MGSystFitComined MGSystFitComined;; cd -;
